name: 'Build Docker'

on:
  push:
    branches:
      - master

permissions:
  contents: read

env:
  IMAGE_NAME: gorules/editor

jobs:
  docker_sass:
    name: 'Build Docker'
    if: "startsWith(github.event.head_commit.message, 'chore(release)')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get Package version
        id: version
        uses: martinbeentjes/npm-get-version-action@v1.3.1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: ${{ env.IMAGE_NAME }}:latest,${{ env.IMAGE_NAME }}:${{steps.version.outputs.current-version}}